#!/bin/sh

set -e

util=bdb

# Automatically added by dh_installdeb
dpkg-maintscript-helper dir_to_symlink /usr/share/doc/bogofilter-bdb /usr/share/doc/bogofilter-common 1.2.4+dfsg1-8~ -- "$@"
# End automatically added section


case "$1" in
    remove|deconfigure)
        if update-alternatives --list bogofilter | grep -q bogofilter-${util}; then
            update-alternatives --quiet --remove bogofilter "/usr/bin/bogofilter-${util}"
        fi
        ;;
    *)
        ;;
esac
