#!/bin/sh
set -e
# Automatically added by dh_apache2
if [ "$1" = "purge" ] ; then
	if true; then
		if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
			. /usr/share/apache2/apache2-maintscript-helper

			for conf in dnssd  ; do
				apache2_invoke dismod $conf  || exit $?
			done
		fi
	fi
fi
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/apache2/mods-available/mod-dnssd.conf /etc/apache2/mods-available/dnssd.conf -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper mv_conffile /etc/apache2/mods-available/mod-dnssd.load /etc/apache2/mods-available/dnssd.load -- "$@"
# End automatically added section
