[Theme]
Id=classic
Name=Classic
Name[af]=Klassiek
Name[ar]=تقليدي
Name[as]=ক্লাসিক
Name[ast]=Clásicu
Name[az]=Klassik
Name[be]=Класічны
Name[bg]=Класическа
Name[bn]=ক্লাসিক
Name[bn_IN]=ক্লাসিক
Name[br]=Klasel
Name[bs]=Klasični
Name[ca]=Clàssic
Name[cs]=Klasický
Name[cy]=Clasurol
Name[da]=Klassisk
Name[de]=Klassisch
Name[dz]=ལེགས་ལྡན།
Name[el]=Κλασικό
Name[en@shaw]=𐑒𐑤𐑨𐑕𐑦𐑒
Name[en_CA]=Classic
Name[en_GB]=Classic
Name[eo]=Klasika
Name[es]=Clásico
Name[et]=Klassikaline
Name[eu]=Klasikoa
Name[fa]=کلاسیک
Name[fi]=Perinteinen
Name[fr]=Classique
Name[fur]=Classic
Name[ga]=Clasaiceach
Name[gl]=Clásico
Name[gu]=શાસ્ત્રિય
Name[he]=קלאסי
Name[hr]=Klasično
Name[hu]=Klasszikus
Name[id]=Klasik
Name[is]=Hefðbundinn
Name[it]=Classico
Name[ja]=クラシック
Name[ka]=კლასიკური
Name[kk]=Классикалық
Name[km]=Classic
Name[kn]=ಕ್ಲಾಸಿಕ್
Name[ko]=클래식
Name[lt]=Klasikinė
Name[lv]=Klasiska
Name[mai]=क्लासिक
Name[mk]=Класично
Name[mn]=Сонгодог
Name[mr]=क्लासिक
Name[nb]=Klassisk
Name[ne]=प्राचीन
Name[nl]=Klassiek
Name[nn]=Klassisk
Name[oc]=Classic
Name[or]=ଚିରପ୍ରତିଷ୍ଠିତ
Name[pa]=ਟਕਸਾਲੀ
Name[pl]=Klasyczny
Name[pt]=Clássico
Name[pt_BR]=Clássico
Name[ro]=Clasic
Name[ru]=Классическая
Name[rw]=Bisanzwe
Name[si]=සුසංගත
Name[sk]=Klasická
Name[sl]=Običajno
Name[sq]=Klasike
Name[sr]=Класични
Name[sr@latin]=Klasični
Name[sv]=Klassisk
Name[ta]=தொன்மையான
Name[te]=సాంప్రదాయక
Name[th]=แบบฉบับ
Name[tr]=Klasik
Name[uk]=Класична
Name[vi]=Cổ điển
Name[xh]=Udidi
Name[zh_TW]=經典

[Pieces]
#Animated=True
File=black_and_white.svg

[Background]
#Image=
Red=0.2
Green=0.6
Blue=0.4
Radius=2

[Mark]
Red=0.5
Green=0.5
Blue=0.5
Width=2

[Border]
Red=0.1
Green=0.1
Blue=0.1
Width=3

[Spacing]
Red=0.1
Green=0.3
Blue=0.2
Width=2

[Highlight]
Red=0.1
Green=0.3
Blue=0.2
Alpha=0.4

[Margin]
#Width=0

[Sound]
Flip=flip-piece.ogg
GameOver=gameover.ogg
